project_id = "vtknmauyvmuaryttnenx"

[functions.send-contact-email]
verify_jwt = false

[functions.send-quote-email]  
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-order-receipt]
verify_jwt = false

[functions.create-paypal-payment]
verify_jwt = false

[functions.capture-paypal-payment]
verify_jwt = false